server:
    port: 8080

spring:
  application:
      name: restaurant-ms

eureka:
    instance:
        prefer-ip-address: true
    client:
        registerWithEureka: false
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true

grpc:
  client:
      product-ms:
        address: discovery:///product-ms
#        address: static://localhost:9090
        negotiation-type: PLAINTEXT